"""initial schema

Revision ID: 50834c9c3273
Revises: 
Create Date: 2026-10-08 00:24:48.455762
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '50834c9c3273'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_type', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('actors', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('actual', sa.Text(), nullable=True),
    sa.Column('surprise', sa.Float(), nullable=True),
    sa.Column('affected_assets', sa.Text(), nullable=True),
    sa.Column('affected_indicators', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_table('forecasts',
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('horizon', sa.String(length=32), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('interval_low', sa.Float(), nullable=True),
    sa.Column('interval_high', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('data_version', sa.String(length=64), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_target'), 'forecasts', ['target'], unique=False)
    op.create_index(op.f('ix_forecasts_target_date'), 'forecasts', ['target_date'], unique=False)
    op.create_table('macro_observations',
    sa.Column('indicator', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('period', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('frequency', sa.String(length=16), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator', 'country', 'period', 'source_name', name='uq_macro_obs')
    )
    op.create_index(op.f('ix_macro_observations_country'), 'macro_observations', ['country'], unique=False)
    op.create_index(op.f('ix_macro_observations_indicator'), 'macro_observations', ['indicator'], unique=False)
    op.create_table('market_observations',
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'observed_at', 'source_name', name='uq_market_obs')
    )
    op.create_index(op.f('ix_market_observations_asset_class'), 'market_observations', ['asset_class'], unique=False)
    op.create_index(op.f('ix_market_observations_symbol'), 'market_observations', ['symbol'], unique=False)
    op.create_table('recommendations',
    sa.Column('asset', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=True),
    sa.Column('horizon', sa.String(length=32), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('downside', sa.Float(), nullable=True),
    sa.Column('probability_up', sa.Float(), nullable=True),
    sa.Column('probability_down', sa.Float(), nullable=True),
    sa.Column('base_scenario', sa.Text(), nullable=True),
    sa.Column('bull_scenario', sa.Text(), nullable=True),
    sa.Column('bear_scenario', sa.Text(), nullable=True),
    sa.Column('tail_risk', sa.Text(), nullable=True),
    sa.Column('evidence_for', sa.Text(), nullable=True),
    sa.Column('evidence_against', sa.Text(), nullable=True),
    sa.Column('main_drivers', sa.Text(), nullable=True),
    sa.Column('main_risks', sa.Text(), nullable=True),
    sa.Column('invalidation', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('data_version', sa.String(length=64), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_asset'), 'recommendations', ['asset'], unique=False)
    op.create_index(op.f('ix_recommendations_decision'), 'recommendations', ['decision'], unique=False)
    op.create_table('sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=True),
    sa.Column('historical_accuracy', sa.Float(), nullable=True),
    sa.Column('correction_rate', sa.Float(), nullable=True),
    sa.Column('independence_score', sa.Float(), nullable=True),
    sa.Column('primary_source_ratio', sa.Float(), nullable=True),
    sa.Column('latency_seconds', sa.Float(), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('collection_method', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('world_states',
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granularity', sa.String(length=16), nullable=True),
    sa.Column('growth_pressure', sa.Float(), nullable=True),
    sa.Column('inflation_pressure', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('financial_stress', sa.Float(), nullable=True),
    sa.Column('geopolitical_risk', sa.Float(), nullable=True),
    sa.Column('energy_risk', sa.Float(), nullable=True),
    sa.Column('trade_risk', sa.Float(), nullable=True),
    sa.Column('political_risk', sa.Float(), nullable=True),
    sa.Column('social_pressure', sa.Float(), nullable=True),
    sa.Column('macro_regime', sa.String(length=32), nullable=True),
    sa.Column('market_regime', sa.String(length=32), nullable=True),
    sa.Column('value_metadata', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_states_captured_at'), 'world_states', ['captured_at'], unique=False)
    op.create_table('claims',
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('predicate', sa.String(length=255), nullable=True),
    sa.Column('object', sa.String(length=512), nullable=True),
    sa.Column('claim_type', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_type'), 'claims', ['claim_type'], unique=False)
    op.create_index(op.f('ix_claims_event_id'), 'claims', ['event_id'], unique=False)
    op.create_index(op.f('ix_claims_subject'), 'claims', ['subject'], unique=False)
    op.create_table('documents',
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('doc_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_hash'), 'documents', ['hash'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_table('entities',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'canonical_name', name='uq_entity_type_name')
    )
    op.create_index(op.f('ix_entities_canonical_name'), 'entities', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_entities_source_id'), 'entities', ['source_id'], unique=False)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_table('forecast_outcomes',
    sa.Column('forecast_id', sa.Uuid(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('actual_bool', sa.String(length=8), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('abs_error', sa.Float(), nullable=True),
    sa.Column('squared_error', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_outcomes_forecast_id'), 'forecast_outcomes', ['forecast_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('forecast_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('expected_effect', sa.Text(), nullable=True),
    sa.Column('affected_assets', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('invalidation_criteria', sa.Text(), nullable=True),
    sa.Column('probability_history', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_forecast_id'), 'scenarios', ['forecast_id'], unique=False)
    op.create_table('articles',
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('entities', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('stance', sa.String(length=64), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('duplicate_cluster', sa.String(length=128), nullable=True),
    sa.Column('event_cluster', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_document_id'), 'articles', ['document_id'], unique=False)
    op.create_index(op.f('ix_articles_duplicate_cluster'), 'articles', ['duplicate_cluster'], unique=False)
    op.create_index(op.f('ix_articles_event_cluster'), 'articles', ['event_cluster'], unique=False)
    op.create_index(op.f('ix_articles_event_id'), 'articles', ['event_id'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('from_entity_id', sa.Uuid(), nullable=False),
    sa.Column('to_entity_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('valid_from', sa.String(length=64), nullable=True),
    sa.Column('valid_to', sa.String(length=64), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relationships_from_entity_id'), 'entity_relationships', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_to_entity_id'), 'entity_relationships', ['to_entity_id'], unique=False)
    op.create_table('evidence',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_document_id'), 'evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_id'), 'evidence', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_source_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_document_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_entity_relationships_to_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_from_entity_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_articles_event_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_event_cluster'), table_name='articles')
    op.drop_index(op.f('ix_articles_duplicate_cluster'), table_name='articles')
    op.drop_index(op.f('ix_articles_document_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_scenarios_forecast_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_forecast_outcomes_forecast_id'), table_name='forecast_outcomes')
    op.drop_table('forecast_outcomes')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_source_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_canonical_name'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_claims_subject'), table_name='claims')
    op.drop_index(op.f('ix_claims_event_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_type'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_world_states_captured_at'), table_name='world_states')
    op.drop_table('world_states')
    op.drop_table('sources')
    op.drop_index(op.f('ix_recommendations_decision'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_asset'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_market_observations_symbol'), table_name='market_observations')
    op.drop_index(op.f('ix_market_observations_asset_class'), table_name='market_observations')
    op.drop_table('market_observations')
    op.drop_index(op.f('ix_macro_observations_indicator'), table_name='macro_observations')
    op.drop_index(op.f('ix_macro_observations_country'), table_name='macro_observations')
    op.drop_table('macro_observations')
    op.drop_index(op.f('ix_forecasts_target_date'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_target'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
