"""phase11: events.event_metadata

Revision ID: f58aab369371
Revises: 69c88e2ff7c5
Create Date: 2026-10-08 15:59:43.708743
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f58aab369371'
down_revision: str | None = '69c88e2ff7c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_metadata')
    # ### end Alembic commands ###
